// LWP kiosk bridge — intercepts explicit new-window navigations and
// Office-document downloads and hands them to the backend instead of
// letting Firefox either spawn a second chromeless --kiosk window (no way
// back — see policies.json's browser.link.open_newwindow lock) or silently
// download into a folder nobody can reach (web-type sessions have no
// persistent home).
//
// LWP_BACKEND_URL / LWP_SESSION_TOKEN come from session.js, generated by
// start.sh at container launch — a WebExtension background script has no
// access to process env directly.

const OFFICE_EXT = new Set([
  "doc", "docx", "xls", "xlsx", "ppt", "pptx", "odt", "ods", "odp",
]);

async function post(path, body) {
  try {
    await fetch(`${LWP_BACKEND_URL}${path}`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Session-Token": LWP_SESSION_TOKEN,
      },
      body: JSON.stringify(body),
    });
  } catch (e) {
    console.error("lwp-kiosk-bridge: request failed", e);
  }
}

function extOf(filename) {
  const name = (filename || "").split(/[\\/]/).pop() || "";
  return name.includes(".") ? name.split(".").pop().toLowerCase() : "";
}

// target="_blank" / window.open() / ctrl+click — Firefox is about to open a
// new window. Close it immediately (it would otherwise be a second
// chromeless --kiosk window with no way back) and send the URL to the real
// Firefox app instead.
browser.webNavigation.onCreatedNavigationTarget.addListener((details) => {
  post("/api/sessions/bridge/open", { url: details.url });
  browser.tabs.remove(details.tabId).catch(() => {});
});

// A download starting. PDFs go straight to the Firefox app (its own PDF.js
// can show/download it there); Office documents go through the attachment
// bridge (fetched server-side, dropped into the user's Nextcloud, opened in
// LibreOffice). Anything else is left alone.
browser.downloads.onCreated.addListener((item) => {
  const ext = extOf(item.filename);
  if (ext === "pdf") {
    browser.downloads.cancel(item.id).catch(() => {});
    post("/api/sessions/bridge/open", { url: item.url });
  } else if (OFFICE_EXT.has(ext)) {
    browser.downloads.cancel(item.id).catch(() => {});
    post("/api/sessions/bridge/attachment", {
      url: item.url,
      filename: (item.filename || "").split(/[\\/]/).pop(),
    });
  }
});
